# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitFeed
  pod 'RxSwift', '~> 3.4'
  pod 'RxCocoa', '~> 3.4'
  pod 'Kingfisher'
end
